"""RefResolver: resolve ref IDs to Appium WebElements.

Faithful port of smartestiroid's android/ref_resolver.py.
Tries locator strategies in order with bounds verification (+-20px).
Falls back to coordinate-based resolution as the last resort.

Extended for WebView: CSS selector, link text, tag name strategies;
context-aware switching before resolution; bounds skip for (0,0,0,0).
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from typing import Any

from appium.webdriver.common.appiumby import AppiumBy
from selenium.webdriver.common.by import By

from appium_cli.utils.paths import latest_snapshot_path, snapshot_artifact_dir, snapshot_artifact_path

from .snapshot import LocatorStrategy, RefEntry

logger = logging.getLogger(__name__)

_BOUNDS_TOLERANCE = 20


class ElementNotFoundError(Exception):
    """Raised when all locator strategies fail to resolve a ref."""

    def __init__(self, ref: str, details: str = ""):
        self.ref = ref
        self.details = details
        super().__init__(
            f"ref '{ref}' cannot be resolved. {details}"
        )


@dataclass(frozen=True)
class ParsedRef:
    """A normalized ref, optionally qualified by snapshot id."""

    ref: str
    snapshot_id: str | None = None

    @property
    def display(self) -> str:
        return f"{self.snapshot_id}:{self.ref}" if self.snapshot_id else self.ref


def parse_ref(ref: str) -> ParsedRef:
    """Normalize ``[ref:x]``, ``ref:x``, ``x``, and ``snapshot-id:x`` forms."""
    clean = ref.strip().strip("[]").removeprefix("ref:")
    if ":" in clean:
        snapshot_id, short_ref = clean.split(":", 1)
        if snapshot_id and short_ref:
            return ParsedRef(ref=short_ref, snapshot_id=snapshot_id)
    return ParsedRef(ref=clean)


class _CoordinateElement:
    """Coordinate-based pseudo-element for tap/gesture operations.

    Provides a minimal WebElement-like interface for coordinate-based actions.
    """

    def __init__(self, x: int, y: int, driver: Any) -> None:
        self.x = x
        self.y = y
        self._driver = driver
        self.id = None  # WebElement compat

    @property
    def location(self) -> dict[str, int]:
        return {"x": self.x, "y": self.y}

    @property
    def size(self) -> dict[str, int]:
        return {"width": 1, "height": 1}


class RefResolver:
    """Resolve ref IDs to Appium WebElements.

    Holds ref -> RefEntry mapping generated by SnapshotGenerator.
    When a tool (tap, type_text, etc.) specifies a ref, resolves it
    to an actual WebElement by trying strategies in order with bounds
    verification.
    """

    def __init__(self) -> None:
        self._ref_map: dict[str, RefEntry] = {}
        self._current_snapshot_id: str | None = None
        self._current_snapshot_metadata: dict[str, Any] = {}
        self._artifact_ref_maps: dict[str, dict[str, RefEntry]] = {}
        self._artifact_metadata: dict[str, dict[str, Any]] = {}

    def register_all(
        self,
        ref_map: dict[str, RefEntry],
        *,
        snapshot_id: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> None:
        """Replace the entire ref map."""
        self._ref_map = dict(ref_map)
        if snapshot_id is not None:
            self.mark_current_snapshot(snapshot_id, metadata)

    def mark_current_snapshot(
        self,
        snapshot_id: str | None,
        metadata: dict[str, Any] | None = None,
    ) -> None:
        """Record which snapshot id the current in-memory refs came from."""
        self._current_snapshot_id = snapshot_id
        self._current_snapshot_metadata = dict(metadata or {})

    def register_context(self, context: str, ref_map: dict[str, RefEntry]) -> None:
        """Replace only refs belonging to *context*, keep others."""
        # Remove old refs from this context
        to_remove = [k for k, v in self._ref_map.items() if v.context == context]
        for k in to_remove:
            del self._ref_map[k]
        # Add new refs
        self._ref_map.update(ref_map)

    def has(self, ref: str) -> bool:
        try:
            return self.require_registered(ref) is not None
        except ElementNotFoundError:
            return False

    def get_entry(self, ref: str) -> RefEntry | None:
        try:
            parsed, entry = self.require_registered(ref)
            return entry
        except ElementNotFoundError:
            return None

    def list_refs(self) -> list[str]:
        return list(self._ref_map.keys())

    def resolve(self, ref: str, driver: Any) -> Any:
        """Resolve ref to Appium WebElement.

        Flow:
        1. If ref's context differs from driver's current context, switch
        2. Try strategies in order
        3. For Web strategies that may match multiple elements (css selector,
           xpath, link text, partial link text, tag name), enumerate ALL
           candidates via find_elements and pick the one whose bounds match.
        4. If bounds mismatch on all candidates, try next strategy
        5. All failed -> ElementNotFoundError

        Args:
            ref: element ref ID
            driver: Appium WebDriver instance

        Returns:
            Appium WebElement or _CoordinateElement

        Raises:
            ElementNotFoundError: all strategies failed
        """
        parsed, entry = self.require_registered(ref)

        if not driver:
            raise ElementNotFoundError(parsed.display, "Driver is not initialized.")

        # Switch to the ref's context if needed
        self._ensure_context(driver, entry.context)

        errors: list[str] = []

        for strategy in entry.strategies:
            try:
                candidates = self._find_candidates(driver, strategy)
                if not candidates:
                    errors.append(f"{strategy.by}={strategy.value}: not found")
                    continue

                # Check bounds on all candidates
                for element in candidates:
                    if self._verify_bounds(element, entry.expected_bounds):
                        logger.info(
                            f"ref '{ref}' resolved via {strategy.by}={strategy.value}"
                            f" (checked {len(candidates)} candidate(s))"
                        )
                        return element

                errors.append(
                    f"{strategy.by}={strategy.value}: bounds mismatch"
                    f" ({len(candidates)} candidate(s) checked)"
                )
            except Exception as e:
                errors.append(f"{strategy.by}={strategy.value}: {e}")

        raise ElementNotFoundError(
            parsed.display,
            f"All strategies failed. Run snapshot() to refresh."
            f" Tried: {'; '.join(errors)}",
        )

    def require_registered(self, ref: str) -> tuple[ParsedRef, RefEntry]:
        """Return a registered entry or raise with stale/current snapshot details."""
        parsed = parse_ref(ref)
        if parsed.snapshot_id:
            self._ensure_qualified_snapshot_available(parsed)
            ref_map = (
                self._ref_map
                if parsed.snapshot_id == self._current_snapshot_id
                else self._artifact_ref_maps.get(parsed.snapshot_id, {})
            )
        else:
            ref_map = self._ref_map
        entry = ref_map.get(parsed.ref)
        if entry is not None:
            return parsed, entry
        raise ElementNotFoundError(parsed.display, self._unknown_ref_details(parsed))

    def _ensure_qualified_snapshot_available(self, parsed: ParsedRef) -> None:
        snapshot_id = parsed.snapshot_id
        if snapshot_id == self._current_snapshot_id:
            return
        if snapshot_id in self._artifact_ref_maps:
            return

        refs_json = self._read_refs_json(snapshot_id)
        if refs_json is None:
            latest_hint = self._latest_hint()
            raise ElementNotFoundError(
                parsed.display,
                f"Snapshot '{snapshot_id}' artifacts were not found. {latest_hint}",
            )

        metadata = {
            key: refs_json[key]
            for key in ("snapshot_id", "source", "screen_id", "context")
            if key in refs_json
        }
        if not self._is_latest_snapshot(metadata):
            latest_hint = self._latest_hint(metadata)
            raise ElementNotFoundError(
                parsed.display,
                f"Snapshot '{snapshot_id}' is stale or not current for its context. {latest_hint}",
            )

        self._artifact_ref_maps[snapshot_id] = self._deserialize_ref_map(refs_json)
        self._artifact_metadata[snapshot_id] = metadata

    def _unknown_ref_details(self, parsed: ParsedRef) -> str:
        if parsed.snapshot_id:
            return (
                f"Ref '{parsed.ref}' is not present in snapshot '{parsed.snapshot_id}'. "
                "Run snapshot() to refresh or choose a ref from that snapshot's refs artifact."
            )

        details = ["Not registered in the current in-memory snapshot."]
        if self._current_snapshot_id:
            details.append(f"Current in-memory snapshot is '{self._current_snapshot_id}'.")

        owner = self._find_latest_snapshot_containing_ref(parsed.ref)
        if owner:
            sid = owner.get("snapshot_id", "unknown")
            context = owner.get("context")
            context_hint = f" (context {context})" if context else ""
            details.append(
                f"Ref exists in latest snapshot '{sid}'{context_hint}; use '{sid}:{parsed.ref}' "
                "or run snapshot() in that context before using a short ref."
            )
        else:
            details.append(self._latest_hint())
        return " ".join(part for part in details if part)

    @staticmethod
    def _read_json(path: Any) -> dict[str, Any] | None:
        try:
            if not path.exists():
                return None
            data = json.loads(path.read_text(encoding="utf-8"))
            return data if isinstance(data, dict) else None
        except (OSError, json.JSONDecodeError, TypeError):
            return None

    @classmethod
    def _read_refs_json(cls, snapshot_id: str | None) -> dict[str, Any] | None:
        if not snapshot_id:
            return None
        return cls._read_json(snapshot_artifact_path(snapshot_id, "refs"))

    @classmethod
    def _read_latest(cls, source: str | None = None, context: str | None = None) -> dict[str, Any] | None:
        return cls._read_json(latest_snapshot_path(source=source, context=context))

    def _is_latest_snapshot(self, metadata: dict[str, Any]) -> bool:
        snapshot_id = metadata.get("snapshot_id")
        if not snapshot_id:
            return False
        candidates = [
            self._read_latest(),
            self._read_latest(
                source=str(metadata.get("source") or "") or None,
                context=str(metadata.get("context") or "") or None,
            ),
        ]
        return any(item and item.get("snapshot_id") == snapshot_id for item in candidates)

    def _latest_hint(self, metadata: dict[str, Any] | None = None) -> str:
        latest = self._read_latest()
        scoped = None
        if metadata:
            scoped = self._read_latest(
                source=str(metadata.get("source") or "") or None,
                context=str(metadata.get("context") or "") or None,
            )

        hints = []
        if latest and latest.get("snapshot_id"):
            hints.append(f"latest snapshot is '{latest['snapshot_id']}'")
        latest_id = latest.get("snapshot_id") if latest else None
        if scoped and scoped.get("snapshot_id") and scoped.get("snapshot_id") != latest_id:
            context = scoped.get("context") or (metadata.get("context") if metadata else None)
            scoped_label = f"latest context snapshot is '{scoped['snapshot_id']}'"
            if context:
                scoped_label += f" for context {context}"
            hints.append(scoped_label)
        if not hints:
            return "Run snapshot() to refresh."
        return "; ".join(hints) + "."

    def _find_latest_snapshot_containing_ref(self, ref: str) -> dict[str, Any] | None:
        seen: set[str] = set()
        snapshot_dir = snapshot_artifact_dir()
        pointers = [latest_snapshot_path()]
        try:
            pointers.extend(sorted(snapshot_dir.glob("latest-*.json")))
        except OSError:
            pass
        for pointer in pointers:
            latest = self._read_json(pointer)
            snapshot_id = str((latest or {}).get("snapshot_id") or "")
            if not snapshot_id or snapshot_id in seen:
                continue
            seen.add(snapshot_id)
            refs_json = self._read_refs_json(snapshot_id)
            refs = refs_json.get("refs", {}) if refs_json else {}
            if isinstance(refs, dict) and ref in refs:
                return refs_json
        return None

    @staticmethod
    def _deserialize_ref_map(refs_json: dict[str, Any]) -> dict[str, RefEntry]:
        refs = refs_json.get("refs", {})
        if not isinstance(refs, dict):
            return {}
        result: dict[str, RefEntry] = {}
        for ref, raw_entry in refs.items():
            if not isinstance(raw_entry, dict):
                continue
            strategies = [
                LocatorStrategy(by=str(strategy.get("by", "")), value=str(strategy.get("value", "")))
                for strategy in raw_entry.get("strategies", [])
                if isinstance(strategy, dict)
            ]
            bounds = raw_entry.get("expected_bounds", (0, 0, 0, 0))
            if not isinstance(bounds, (list, tuple)) or len(bounds) != 4:
                bounds = (0, 0, 0, 0)
            result[str(ref)] = RefEntry(
                strategies=strategies,
                expected_bounds=tuple(int(value) for value in bounds),
                role=str(raw_entry.get("role", "")),
                name=str(raw_entry.get("name", "")),
                context=str(raw_entry.get("context") or refs_json.get("context") or "NATIVE_APP"),
                source_type=str(raw_entry.get("source_type") or refs_json.get("source") or "native"),
                action_target_ref=raw_entry.get("action_target_ref"),
            )
        return result

    def resolve_or_none(self, ref: str, driver: Any) -> Any | None:
        try:
            return self.resolve(ref, driver)
        except ElementNotFoundError:
            return None

    @staticmethod
    def _ensure_context(driver: Any, context: str) -> None:
        """Switch driver to the ref's context if it differs."""
        try:
            current = driver.current_context or "NATIVE_APP"
        except Exception:
            return
        if current != context:
            try:
                driver.switch_to.context(context)
            except Exception as exc:
                logger.warning("Failed to switch to context %s: %s", context, exc)

    @staticmethod
    def _find_candidates(driver: Any, strategy: LocatorStrategy) -> list[Any]:
        """Find all candidate elements for a strategy.

        For strategies that may match multiple elements (css selector, xpath,
        link text, partial link text, tag name), returns all matches so the
        caller can verify bounds on each. For native id/accessibility_id and
        coordinates, returns a single-element list.
        """
        by = strategy.by
        value = strategy.value

        if by == "id":
            try:
                return [driver.find_element(AppiumBy.ID, value)]
            except Exception:
                return []

        if by == "accessibility_id":
            try:
                return [driver.find_element(AppiumBy.ACCESSIBILITY_ID, value)]
            except Exception:
                return []

        if by == "xpath":
            try:
                return driver.find_elements(AppiumBy.XPATH, value) or []
            except Exception:
                return []

        if by == "css selector":
            try:
                return driver.find_elements(By.CSS_SELECTOR, value) or []
            except Exception:
                return []

        if by == "link text":
            try:
                return driver.find_elements(By.LINK_TEXT, value) or []
            except Exception:
                return []

        if by == "partial link text":
            try:
                return driver.find_elements(By.PARTIAL_LINK_TEXT, value) or []
            except Exception:
                return []

        if by == "tag name":
            try:
                return driver.find_elements(By.TAG_NAME, value) or []
            except Exception:
                return []

        if by == "coordinates":
            try:
                parts = value.split(",")
                x, y = int(parts[0]), int(parts[1])
                return [_CoordinateElement(x, y, driver)]
            except Exception:
                return []

        return []

    @staticmethod
    def _find_by_strategy(driver: Any, strategy: LocatorStrategy) -> Any | None:
        by = strategy.by
        value = strategy.value

        if by == "id":
            try:
                return driver.find_element(AppiumBy.ID, value)
            except Exception:
                return None

        if by == "accessibility_id":
            try:
                return driver.find_element(AppiumBy.ACCESSIBILITY_ID, value)
            except Exception:
                return None

        if by == "xpath":
            try:
                return driver.find_element(AppiumBy.XPATH, value)
            except Exception:
                return None

        if by == "css selector":
            try:
                return driver.find_element(By.CSS_SELECTOR, value)
            except Exception:
                return None

        if by == "link text":
            try:
                return driver.find_element(By.LINK_TEXT, value)
            except Exception:
                return None

        if by == "partial link text":
            try:
                return driver.find_element(By.PARTIAL_LINK_TEXT, value)
            except Exception:
                return None

        if by == "tag name":
            try:
                return driver.find_element(By.TAG_NAME, value)
            except Exception:
                return None

        if by == "coordinates":
            try:
                parts = value.split(",")
                x, y = int(parts[0]), int(parts[1])
                return _CoordinateElement(x, y, driver)
            except Exception:
                return None

        return None

    @staticmethod
    def _verify_bounds(
        element: Any,
        expected: tuple[int, int, int, int],
    ) -> bool:
        """Check if element bounds match expected bounds within tolerance.

        Skips verification for (0,0,0,0) bounds (web refs without precise bounds).
        """
        if isinstance(element, _CoordinateElement):
            return True

        # Skip bounds check for zero bounds (web elements may lack them)
        if expected == (0, 0, 0, 0):
            return True

        try:
            location = element.location
            size = element.size
            actual_x1 = location["x"]
            actual_y1 = location["y"]
            actual_x2 = actual_x1 + size["width"]
            actual_y2 = actual_y1 + size["height"]

            ex1, ey1, ex2, ey2 = expected
            return (
                abs(actual_x1 - ex1) <= _BOUNDS_TOLERANCE
                and abs(actual_y1 - ey1) <= _BOUNDS_TOLERANCE
                and abs(actual_x2 - ex2) <= _BOUNDS_TOLERANCE
                and abs(actual_y2 - ey2) <= _BOUNDS_TOLERANCE
            )
        except Exception:
            return True

    def clear(self) -> None:
        self._ref_map.clear()
        self._current_snapshot_id = None
        self._current_snapshot_metadata = {}
        self._artifact_ref_maps.clear()
        self._artifact_metadata.clear()
