"""RefResolver: resolve ref IDs to Appium WebElements.

Faithful port of smartestiroid's android/ref_resolver.py.
Tries locator strategies in order with bounds verification (+-20px).
Falls back to coordinate-based resolution as the last resort.

Extended for WebView: CSS selector, link text, tag name strategies;
context-aware switching before resolution; bounds skip for (0,0,0,0).
"""

from __future__ import annotations

import logging
from typing import Any

from appium.webdriver.common.appiumby import AppiumBy
from selenium.webdriver.common.by import By

from .snapshot import LocatorStrategy, RefEntry

logger = logging.getLogger(__name__)

_BOUNDS_TOLERANCE = 20


class ElementNotFoundError(Exception):
    """Raised when all locator strategies fail to resolve a ref."""

    def __init__(self, ref: str, details: str = ""):
        self.ref = ref
        self.details = details
        super().__init__(
            f"ref '{ref}' cannot be resolved. {details}"
        )


class _CoordinateElement:
    """Coordinate-based pseudo-element for tap/gesture operations.

    Provides a minimal WebElement-like interface for coordinate-based actions.
    """

    def __init__(self, x: int, y: int, driver: Any) -> None:
        self.x = x
        self.y = y
        self._driver = driver
        self.id = None  # WebElement compat

    @property
    def location(self) -> dict[str, int]:
        return {"x": self.x, "y": self.y}

    @property
    def size(self) -> dict[str, int]:
        return {"width": 1, "height": 1}


class RefResolver:
    """Resolve ref IDs to Appium WebElements.

    Holds ref -> RefEntry mapping generated by SnapshotGenerator.
    When a tool (tap, type_text, etc.) specifies a ref, resolves it
    to an actual WebElement by trying strategies in order with bounds
    verification.
    """

    def __init__(self) -> None:
        self._ref_map: dict[str, RefEntry] = {}

    def register_all(self, ref_map: dict[str, RefEntry]) -> None:
        """Replace the entire ref map."""
        self._ref_map = dict(ref_map)

    def register_context(self, context: str, ref_map: dict[str, RefEntry]) -> None:
        """Replace only refs belonging to *context*, keep others."""
        # Remove old refs from this context
        to_remove = [k for k, v in self._ref_map.items() if v.context == context]
        for k in to_remove:
            del self._ref_map[k]
        # Add new refs
        self._ref_map.update(ref_map)

    def has(self, ref: str) -> bool:
        return ref in self._ref_map

    def get_entry(self, ref: str) -> RefEntry | None:
        return self._ref_map.get(ref)

    def list_refs(self) -> list[str]:
        return list(self._ref_map.keys())

    def resolve(self, ref: str, driver: Any) -> Any:
        """Resolve ref to Appium WebElement.

        Flow:
        1. If ref's context differs from driver's current context, switch
        2. Try strategies in order
        3. After finding an element, verify bounds (+-20px)
        4. If bounds mismatch, try next strategy
        5. All failed -> ElementNotFoundError

        Args:
            ref: element ref ID
            driver: Appium WebDriver instance

        Returns:
            Appium WebElement or _CoordinateElement

        Raises:
            ElementNotFoundError: all strategies failed
        """
        ref = ref.strip("[]").removeprefix("ref:")
        entry = self._ref_map.get(ref)
        if not entry:
            raise ElementNotFoundError(
                ref, "Not registered. Run snapshot() to refresh."
            )

        if not driver:
            raise ElementNotFoundError(ref, "Driver is not initialized.")

        # Switch to the ref's context if needed
        self._ensure_context(driver, entry.context)

        errors: list[str] = []

        for strategy in entry.strategies:
            try:
                element = self._find_by_strategy(driver, strategy)
                if element is None:
                    errors.append(f"{strategy.by}={strategy.value}: not found")
                    continue

                if self._verify_bounds(element, entry.expected_bounds):
                    logger.info(
                        f"ref '{ref}' resolved via {strategy.by}={strategy.value}"
                    )
                    return element
                else:
                    errors.append(f"{strategy.by}={strategy.value}: bounds mismatch")
            except Exception as e:
                errors.append(f"{strategy.by}={strategy.value}: {e}")

        raise ElementNotFoundError(
            ref,
            f"All strategies failed. Run snapshot() to refresh."
            f" Tried: {'; '.join(errors)}",
        )

    def resolve_or_none(self, ref: str, driver: Any) -> Any | None:
        try:
            return self.resolve(ref, driver)
        except ElementNotFoundError:
            return None

    @staticmethod
    def _ensure_context(driver: Any, context: str) -> None:
        """Switch driver to the ref's context if it differs."""
        try:
            current = driver.current_context or "NATIVE_APP"
        except Exception:
            return
        if current != context:
            try:
                driver.switch_to.context(context)
            except Exception as exc:
                logger.warning("Failed to switch to context %s: %s", context, exc)

    @staticmethod
    def _find_by_strategy(driver: Any, strategy: LocatorStrategy) -> Any | None:
        by = strategy.by
        value = strategy.value

        if by == "id":
            try:
                return driver.find_element(AppiumBy.ID, value)
            except Exception:
                return None

        if by == "accessibility_id":
            try:
                return driver.find_element(AppiumBy.ACCESSIBILITY_ID, value)
            except Exception:
                return None

        if by == "xpath":
            try:
                return driver.find_element(AppiumBy.XPATH, value)
            except Exception:
                return None

        if by == "css selector":
            try:
                return driver.find_element(By.CSS_SELECTOR, value)
            except Exception:
                return None

        if by == "link text":
            try:
                return driver.find_element(By.LINK_TEXT, value)
            except Exception:
                return None

        if by == "partial link text":
            try:
                return driver.find_element(By.PARTIAL_LINK_TEXT, value)
            except Exception:
                return None

        if by == "tag name":
            try:
                return driver.find_element(By.TAG_NAME, value)
            except Exception:
                return None

        if by == "coordinates":
            try:
                parts = value.split(",")
                x, y = int(parts[0]), int(parts[1])
                return _CoordinateElement(x, y, driver)
            except Exception:
                return None

        return None

    @staticmethod
    def _verify_bounds(
        element: Any,
        expected: tuple[int, int, int, int],
    ) -> bool:
        """Check if element bounds match expected bounds within tolerance.

        Skips verification for (0,0,0,0) bounds (web refs without precise bounds).
        """
        if isinstance(element, _CoordinateElement):
            return True

        # Skip bounds check for zero bounds (web elements may lack them)
        if expected == (0, 0, 0, 0):
            return True

        try:
            location = element.location
            size = element.size
            actual_x1 = location["x"]
            actual_y1 = location["y"]
            actual_x2 = actual_x1 + size["width"]
            actual_y2 = actual_y1 + size["height"]

            ex1, ey1, ex2, ey2 = expected
            return (
                abs(actual_x1 - ex1) <= _BOUNDS_TOLERANCE
                and abs(actual_y1 - ey1) <= _BOUNDS_TOLERANCE
                and abs(actual_x2 - ex2) <= _BOUNDS_TOLERANCE
                and abs(actual_y2 - ey2) <= _BOUNDS_TOLERANCE
            )
        except Exception:
            return True

    def clear(self) -> None:
        self._ref_map.clear()
